@startuml
left to right direction

package "银行系统" {
  usecase "开设账户" as UC1
  usecase "转账" as UC2
  usecase "存款" as UC3
  usecase "取款" as UC4
  usecase "查询余额" as UC5
  usecase "申请贷款" as UC6
  usecase "设置/更改支付密码" as UC7
  usecase "在线支付" as UC8
  usecase "设置账户通知和提醒" as UC9
  usecase "查看交易历史记录" as UC10
  usecase "外币兑换" as UC11
}

actor "客户" as A1
actor "银行员工" as A2

A1 ---> UC1 : 请求
A1 --> UC2 : 请求
A1 --> UC3 : 请求
A1 --> UC4 : 请求
A1 --> UC5 : 查询
A1 --> UC6 : 申请
A1 --> UC7 : 设置
A1 --> UC8 : 支付
A1 --> UC9 : 设置
A1 --> UC10 : 查看
A1 --> UC11 : 兑换

A2 --> UC1 : 执行
A2 --> UC2 : 执行
A2 --> UC3 : 协助
A2 --> UC4 : 协助
A2 --> UC6 : 审核
A2 --> UC11 : 协助

@enduml
