@startuml
'参考资料  https://pubs.opengroup.org/togaf-standard/business-architecture/organization-mapping.html

package "全球零售企业有限公司" #SkyBlue {
  [全球零售\n企业有限公司]
}

package "业务单元" #LightGreen {
  [在线商店]
  [零售运营]
   [中央运营]
   [产品管理]
}

package "部门" #MediumPurple {
 
  [人力资源]
  [IT]
  [财务]
  [销售与市场营销]
  [产品设计]
  [美国商店]
  [英国商店]
  [日本商店]
}

package "外部合作伙伴" #Orange {
  [产品供应商]
 
  [仓库]
  [Web服务]
}

package "合作团队" #Yellow {
  [零售策略团队]
   [质量保证]
}

[全球零售\n企业有限公司] --> [中央运营]
[全球零售\n企业有限公司] --> [在线商店]
[全球零售\n企业有限公司] --> [零售运营]

[中央运营] --> [人力资源]
[中央运营] --> [IT]
[中央运营] --> [财务]
[中央运营] --> [销售与市场营销]
[中央运营] --> [产品设计]
[中央运营] --> [仓库]

[零售运营] --> [美国商店]
[零售运营] --> [英国商店]
[零售运营] --> [日本商店]
[零售运营] <--> [销售与市场营销]


[在线商店] --> [Web服务]
[在线商店] <--> [仓库]

 [IT] .. [产品管理]

[产品设计] --> [产品供应商]
[产品设计] --> [质量保证]


[销售与市场营销] <--> [零售策略团队]
[销售与市场营销] -->[产品设计]

[产品供应商]-->[质量保证]


'[Web服务] --> [仓库]

@enduml
