@startuml

class "电商公司" {
}

class "CEO" {
}

class "营销部" {
   - 广告团队
   - 社交媒体团队
   - 市场研究团队
   - 品牌策略团队
}

class "技术部" {
   - 前端团队
   - 后端团队
   - 数据团队
   - 移动应用团队
   - 安全团队
}

class "运营部" {
   - 客服团队
   - 物流团队
   - 供应链团队
   - 产品管理团队
}

class "人事部" {
   - 招聘团队
   - 员工关系团队
   - 培训与发展团队
}

class "财务部" {
   - 会计团队
   - 财务策略团队
   - 税务团队
}

class "策略部" {
   - 业务发展团队
   - 市场洞察团队
   - 竞争对手分析团队
}

class "合作伙伴关系部" {
   - 国内合作伙伴团队
   - 国际合作伙伴团队
   - 大型企业合作团队
}

"电商公司" o-- "CEO" : Contains >
"CEO" o-- "营销部" : Manages >
"CEO" o-- "技术部" : Manages >
"CEO" o-- "运营部" : Manages >
"CEO" o-- "人事部" : Manages >
"CEO" o-- "财务部" : Manages >
"CEO" o-- "策略部" : Manages >
"CEO" o-- "合作伙伴关系部" : Manages >

@enduml
