@startuml
left to right direction
skinparam packageStyle rect

package "电商平台" {

    usecase "浏览商品" as UC1
    usecase "搜索商品" as UC2
    usecase "查看商品详情" as UC3
    usecase "查看卖家信息" as UC4
    usecase "添加到购物车" as UC5
    usecase "查看购物车" as UC6
    usecase "结账购买" as UC7
    usecase "选择支付方式" as UC8
    usecase "确认收货" as UC9
    usecase "查看订单状态" as UC10
    usecase "查看/管理个人账户" as UC11
    usecase "留下商品评价" as UC12
    usecase "参与秒杀/团购活动" as UC13
    usecase "浏览/使用优惠券" as UC14
    usecase "申请退款/退货" as UC15
    usecase "在线客服咨询" as UC16
    usecase "查看/修改收货地址" as UC17

}

'UC7-->UC8

actor "顾客" as Customer
actor "客服" as Support
actor "卖家" as Seller
'actor "支付平台" as PaymentPlatform

Customer --> UC1
Customer --> UC2
Customer --> UC3
Customer --> UC4
Customer --> UC5
Customer --> UC6
Customer --> UC7
Customer --> UC9
Customer --> UC10
Customer --> UC11
Customer --> UC12
Customer --> UC13
Customer --> UC14
Customer --> UC15
Customer --> UC16
Customer -------> UC17
Customer --> UC8 : <<extend>>

/'Seller -left-> UC3
Seller -left-> UC13
Seller -left-> UC14
Seller -left-> UC4'/
UC13 <--- Seller
UC14 <--- Seller
UC4 <--- Seller
UC3 <--- Seller

UC10 <-- Support
UC15 <-- Support
UC16 <-- Support

/'Support --> UC10
Support --> UC15
Support --> UC16'/

'PaymentPlatform <-- UC8
@enduml
