@startuml
'title 电商公司 业务足迹图

skinparam rectangle {
  BackgroundColor transparent
  BorderColor black
  roundcorner 25
}

' 组件定义
package "组织单位" {
  rectangle "销售部门" as SalesDept
  rectangle "客户服务部门" as CustomerServiceDept
}

'package "业务领域" {
 ' rectangle "进入市场" as GoToMarket
'}

package "业务目标" {
  rectangle "提高客户满意度" as ImproveCustomerSatisfaction
}

package "业务流程" {
  rectangle "客户投诉处理" as CustomerRelationshipManagement
  rectangle "客户身份验证" as CustomerIDChK
}

package "业务服务" {
  rectangle "在线客户支持聊天" as CustomerSupport
}

package "业务能力" as Busiability {
  rectangle "客户支持管理" as CustomerSupportmg
  rectangle "客户关系管理" as Customerrelmg
}

' 组件关系
'GoToMarket --> SalesDept : "参与"
'SalesDept --> CustomerRelationshipManagement : "指挥"
CustomerServiceDept--> Busiability  : "使用"
ImproveCustomerSatisfaction <-- CustomerSupport : "支持"
'SalesManagement --> SalesDept : "使能"

' 其他相关组件
rectangle "传统 CRM" as LegacyCRM
CustomerRelationshipManagement <-- LegacyCRM : "自动化"
CustomerIDChK <-- LegacyCRM : "自动化"
CustomerRelationshipManagement -right-> CustomerSupport: "支持"
CustomerSupportmg -left-> CustomerRelationshipManagement: "被实现"
Customerrelmg --> CustomerIDChK: "被实现"
CustomerIDChK --> CustomerSupport: "支持"

@enduml
