@startuml

package "数据中心1" {
    node "Web服务器" as WS {
        [Web应用程序]
    }
    node "应用服务器" as AS {
        [订单处理服务]
        [库存管理服务]
        [用户资料服务]
    }
    database "数据库服务器" as DB {
        [商品数据库]
        [用户数据库]
        [订单数据库]
    }
}

package "数据中心2" {
    [备份数据库]
}

'WS --> AS: REST/HTTP
'AS --> DB: JDBC/SQL

[Web应用程序] --> [订单处理服务]: API调用\n REST/HTTP \n 150QPS
[Web应用程序] --> [库存管理服务]: API调用\n REST/HTTP\n 80QPS
[Web应用程序] --> [用户资料服务]: API调用\n REST/HTTP\n 20QPS

[订单处理服务] --> [订单数据库]: CRUD操作\n JDBC/SQL
[库存管理服务] --> [商品数据库]: CRUD操作\n JDBC/SQL
[用户资料服务] --> [用户数据库]: CRUD操作\n JDBC/SQL

DB --> [备份数据库]: 数据复制

@enduml
