@startuml

package "数据中心（北京）" {
  [应用服务器集群]
  [数据库服务器集群]
  
  [商品列表服务] --> [应用服务器集群]
  [支付服务] --> [应用服务器集群]
  [用户管理服务] --> [应用服务器集群]
  [订单服务] --> [应用服务器集群]
  [物流服务] --> [应用服务器集群]
  [应用服务器集群] --> [数据库服务器集群]
}

package "销售和客户服务部门（上海）" {
  [web服务器1]
  [商品浏览应用] --> [web服务器1] : 交互
  [web服务器1] --> [商品列表服务] : 请求数据
  [物流查询应用] --> [web服务器1] : 交互
  [web服务器1] --> [物流服务] : 查询物流信息
}

package "财务部门（杭州）" {
  [web服务器2]
  [订单管理应用] --> [web服务器2] : 交互
  [web服务器2] --> [订单服务] : 提交订单
  [支付审核应用] --> [web服务器2] : 交互
  [web服务器2] --> [支付服务] : 提交支付
}

package "后台和物流部门（南京）" {
  [web服务器3]
  [后台管理应用] --> [web服务器3] : 交互
  [web服务器3] --> [订单服务] : 管理订单
  [物流管理应用] --> [web服务器3] : 交互
  [web服务器3] --> [物流服务] : 更新物流信息
}

@enduml
