@startuml

skinparam defaultTextAlignment center
skinparam fontsize 28
skinparam nodesep 20
skinparam packageStyle rect

package "Internet" {
    [用户设备] --> [CDN分发节点] : HTTPS
}

package "DMZ" as aDMZ {
    [API网关]
    [SSL/TLS加密终结]
    [负载均衡器]
    [CDN分发节点]
    
    [API网关] -left-> [SSL/TLS加密终结]: HTTPS
    [SSL/TLS加密终结] -down-> [负载均衡器] : HTTP/2.0
}

package "Intranet - 电商平台" {
    node "应用服务器集群" as appserver {
        [商品管理服务]
        [订单管理服务]
        [客户关系管理服务]
    }

    database "关系数据库" as DBserver {
        [商品数据]
        [订单数据]
        [客户数据]
    }

    node "缓存服务器集群" as cacheserver {
        [缓存服务]
    }

    node "文件存储服务" as fileserver {
        [图片存储]
        [文档存储]
    }

    [用户设备] -left->  [API网关] 
    [负载均衡器] --> appserver : HTTP/1.1
    appserver --> DBserver : JDBC
    appserver --> cacheserver: Memcached Protocol
    appserver --> fileserver : SFTP
}

@enduml
