@startuml



package "数据中心（北京）" {
  
   package "应用服务器集群" as a1 {
 
    [商品列表服务] 
    [支付服务] 
    [用户管理服务] 
    [订单服务] 
    [物流服务] 
  
  }
   package "数据库服务器集群" as a2 {
     [数据库服务] 
   }
}



[商品列表服务] --> [数据库服务] 
   [支付服务]  --> [数据库服务] 
    [用户管理服务]   --> [数据库服务] 
   [订单服务]   -->[数据库服务] 
   [物流服务]   --> [数据库服务] 

package "销售和客户服务部门（上海）" {
  package "web服务器1" {
  [商品浏览应用] --> [商品列表服务] : 请求数据
  [物流查询应用] --> [物流服务] : 查询物流信息
  
  }
}

package "财务部门（杭州）" {
  package web服务器2 {
  [订单管理应用] -->[订单服务] : 提交订单 
  [支付审核应用] --> [支付服务] : 提交支付
  
  }
}

package "后台和物流部门（南京）" {
  package web服务器3 {
  [后台管理应用] --> [订单服务] : 管理订单
  [物流管理应用] --> [物流服务] : 更新物流信息
  
  }
}

@enduml
