@startuml

cloud "云平台 - 可用区A" as CloudA {
  package [服务器A集群] {
  
  [商品列表服务A]
  [支付服务A] 
  [用户管理服务A] 
  [订单服务A] 
  [物流服务A] 
  }
}

cloud "云平台 - 可用区B" as CloudB {
  package [服务器B集群] {
  
  [商品列表服务B]
  [支付服务B] 
  [用户管理服务B] 
  [订单服务B] 
  [物流服务B] 
  }
}

database "云平台 - 数据库A区" as DBA {
  [商品数据A]
  [用户数据A]
  [订单数据A]
  [物流数据A]
}

database "云平台 - 数据库B区" as DBB {
  [商品数据B]
  [用户数据B]
  [订单数据B]
  [物流数据B]
}

[商品列表服务A] --> DBA : 读写数据
[商品列表服务B] --> DBB : 读写数据
[支付服务A] --> DBA : 读写数据
[支付服务B] --> DBB : 读写数据
[订单服务A] --> DBA : 读写数据
[订单服务B] --> DBB : 读写数据
[物流服务A] --> DBA : 读写数据
[物流服务B] --> DBB : 读写数据
[用户管理服务A] --> DBA : 读写数据
[用户管理服务B] --> DBB : 读写数据

DBA <--> DBB : 数据同步

package "前端" as aaa1 {
  [APP/网站/......] as aaa
 
}

aaa --> [商品列表服务A]

 aaa --> [商品列表服务A] : 请求数据A
  aaa --> [商品列表服务B] : 请求数据B
 
 aaa --> [物流服务A] : 查询物流信息A
 aaa --> [物流服务B] : 查询物流信息B
 
  aaa --> [订单服务A] : 提交订单A
  aaa --> [订单服务B] : 提交订单B
 
 aaa --> [支付服务A] : 提交支付A
  aaa--> [支付服务B] : 提交支付B

  aaa --> [用户管理服务A] : 提交用户管理A
  aaa--> [用户管理服务B] : 提交用户管理B

@enduml
