@startuml
'left to right direction
skinparam packageStyle rect

actor 第三方支付网关
actor 财务团队
actor 销售团队
actor 客户 
actor IT团队

package "数据中心" {
  usecase "订单" as o1
  usecase "付款" as o2
  usecase "客户资料" as o3
  usecase "商品" as o4
  usecase "反馈" as o5
  o1 -[hidden]-> o2
  o2 -[hidden]-> o3
  o3 -[hidden]-> o4
  o4 -[hidden]-> o5
}

第三方支付网关 -right-> o1 : R
第三方支付网关 --> o3 : R/U
财务团队 -right-> o1 : R
财务团队 --> o3 : R/U

销售团队 -left-> o1 : R/U
第三方支付网关 -[hidden]-> 销售团队
销售团队 -left-> o2 : R
销售团队 -l-> o3 : R

@enduml