@startuml
left to right direction
skinparam packageStyle rect

actor 第三方支付网关
actor 财务团队
actor 销售团队
actor 客户 
actor IT团队


package "订单信息" {
  usecase "订单" as o1
  客户 --> o1 : CRUD
  销售团队 --> o1 : R/U
  财务团队 --> o1 : R
  IT团队 --> o1 : R/U
  第三方支付网关 --> o1 : R
}

package "客户详细资料" {
  usecase "客户资料" as o2
  客户 --> o2 : R/U
  销售团队 --> o2 : R
  IT团队 --> o2 : R/U
}

package "付款记录" {
  usecase "付款" as o3
  客户 --> o3 : R
  销售团队 --> o3 : R
  财务团队 --> o3 : R/U
  IT团队 --> o3 : R
  第三方支付网关 --> o3 : R/U
}

package "商品目录" {
  usecase "商品" as o4
  客户 --> o4 : R
  销售团队 --> o4 : R
  IT团队 --> o4 : R/U
}

package "客户反馈" {
  usecase "反馈" as o5
  客户 --> o5 : CRUD
  销售团队 --> o5 : R
  IT团队 --> o5 : R/U
}

'财务团队 -[hidden]->  第三方支付网关
'第三方支付网关 -[hidden]->  o3


@enduml
